{
  "tests": [
    {
      "query_file": "moveIssueToSuspectedIssue.graphql",
      "result": { "data": { "moveAnnotationIssue": true } }
    },
    {
      "query_file": "moveSuspectedIssueToIssue.graphql",
      "result": { "data": { "moveAnnotationIssue": true } }
    },
    {
      "query_file": "addIssue.graphql",
      "result": { "data": { "addAnnotationIssue": true } }
    },
    {
      "query_file": "addSuspectedIssue.graphql",
      "result": { "data": { "addAnnotationIssue": true } }
    },
    {
      "query_file": "editNote.graphql",
      "result": { "data": { "editAnnotationNote":  true } }
    },
    {
      "query_file": "editNoteInvalid.graphql",
      "result": {
        "errors": [
          {
            "message": "couldn't update note: note is out of sync, please try again",
            "path": [
              "editAnnotationNote"
            ],
            "extensions": {
              "code": "INTERNAL_SERVER_ERROR"
            }
          }
        ],
        "data": null
      }
    }
  ]
}
